// <auto-generated />
using System;
using DMPackageManager.Website.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DMPackageManager.Website.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20210706191050_ExtraURLs")]
    partial class ExtraURLs
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("DMPackageManager.Website.Models.Database.DatabaseUser", b =>
                {
                    b.Property<long>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("username")
                        .HasColumnType("longtext");

                    b.HasKey("userId");

                    b.ToTable("users");
                });

            modelBuilder.Entity("DMPackageManager.Website.Models.Database.Package", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("creation_date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("description")
                        .HasColumnType("longtext");

                    b.Property<string>("documentation_url")
                        .HasColumnType("longtext");

                    b.Property<long?>("owneruserId")
                        .HasColumnType("bigint");

                    b.Property<string>("package_name")
                        .HasColumnType("longtext");

                    b.Property<string>("source_url")
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.HasIndex("owneruserId");

                    b.ToTable("packages");
                });

            modelBuilder.Entity("DMPackageManager.Website.Models.Database.PackageVersion", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("download_count")
                        .HasColumnType("int");

                    b.Property<int?>("packageid")
                        .HasColumnType("int");

                    b.Property<DateTime>("release_date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("release_notes")
                        .HasColumnType("longtext");

                    b.Property<string>("version")
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.HasIndex("packageid");

                    b.ToTable("package_releases");
                });

            modelBuilder.Entity("DMPackageManager.Website.Models.Database.Package", b =>
                {
                    b.HasOne("DMPackageManager.Website.Models.Database.DatabaseUser", "owner")
                        .WithMany()
                        .HasForeignKey("owneruserId");

                    b.Navigation("owner");
                });

            modelBuilder.Entity("DMPackageManager.Website.Models.Database.PackageVersion", b =>
                {
                    b.HasOne("DMPackageManager.Website.Models.Database.Package", "package")
                        .WithMany()
                        .HasForeignKey("packageid");

                    b.Navigation("package");
                });
#pragma warning restore 612, 618
        }
    }
}
