// <auto-generated />
using System;
using DMPackageManager.Website.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DMPackageManager.Website.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("DMPackageManager.Website.Models.Database.Package", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("creation_date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("description")
                        .HasColumnType("longtext");

                    b.Property<string>("latest_version")
                        .HasColumnType("longtext");

                    b.Property<int>("owner")
                        .HasColumnType("int");

                    b.Property<string>("package_name")
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("packages");
                });
#pragma warning restore 612, 618
        }
    }
}
